### ISSUE TITLE
SlideMenuView push duplicate screen

### ISSUE THREAD

**Issue by levannga1125** [aspect-apps/react-native-navigation-drawer-extension#31]
I'm using SideMenuView and there is button in SlideMenuView, when i click button will push new screen, SlideMenu is closed, later I swipe to make the Slide Menu show and click button again. It's duplicate screen in stack, somebody give me suggestion. SORRY for my English.

**Comment by rodriigovieira** [comment]
Hey @levannga1125!

I was able to replicate this issue, it happens due to the way that `react-native-navigation` works. You can push the same screen multiple times.

A workaround for this would be to track the name of the last page that was opened using the events that `react-native-navigation` provides, and then checking if the name of the last component is the same as the one the user's trying to push.

It would be something like this:

```
let lastPageName = '';
const CurrentComponentName = 'CustomDrawer';

Navigation.events().registerComponentDidAppearListener((event) => {
  if (event.componentName !== CurrentComponentName) {
    lastPageName = event.componentName;
  }
});
```

And on the function to navigate to the screen:

```
const openAnotherPage = (pageName) => {
    RNNDrawer.dismissDrawer();

    if (pageName === lastPageName) {
      return;
    }

    Navigation.push(props.parentComponentId, {
      component: {
        name: pageName,
      },
    });
  };
```

Please bear in mind that this was not tested, it is simply an idea on how this could be achieved.

Let me know if this makes sense to you or if you have any other questions.

**Comment by lukebrandonfarrell** [comment]
Above solution should work @levannga1125. This is out of scope for the library
